### ISSUE TITLE
PS1 polluted with `[nix-shell] `

### ISSUE THREAD

**Issue by varunpatro** [spwhitt/nix-zsh-completions#10]
### System

- nix-zsh-completions version: 
- ZSH version: 5.4.2 
- NIX_PATH: /nix/var/nix/profiles/per-user/root/channels 

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.3.0, macOS 10.13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

### Completion trace

Some how my PS1 is getting polluted with a `[nix-shell] ` prefix

Here's a gif: https://asciinema.org/a/IQjI1TGgisnn9zm5IW8A0rsfv

**Comment by hedning** [comment]
How is `nix-zsh-completions` installed? Do you source the (nix.plugin.zsh)[https://github.com/spwhitt/nix-zsh-completions/blob/master/nix.plugin.zsh]? It's the only thing that touch the prompt, and isn't needed.

Also how did you conclude that the culprit was `nix-zsh-completions`, apart from the before mentioned file it doesn't modify the prompt at all.

**Comment by varunpatro** [comment]
I use `oh-my-zsh` and following the guide, I configured my `.zshrc` to have the line:

`plugins=(git z zsh-autosuggestions osx zsh-syntax-highlighting nix)`

When I remove the `nix` plugin, the PS1 doesn't get polluted and the nix autocomplete is deactivated as well. From this, it looks like the PS1 prefix appears only when the nix package is active.

**Comment by hedning** [comment]
Right, looks like this is intended behavior when its installed as an `oh-my-zsh` plugin: https://github.com/spwhitt/nix-zsh-completions/blob/master/nix.plugin.zsh#L12

If you `print $IN_NIX_SHELL` when your prompt contains `[nix-shell]` it will probably produce `1` indicating you're in a nix-shell environment, which then is indicated in the prompt.

If you dislike the behavior a quick fix is to delete this line, https://github.com/spwhitt/nix-zsh-completions/blob/master/nix.plugin.zsh#L24, in your local repo.

I agree that it's weird that installing as a plugin through `oh-my-zsh` modifies the prompt in this way, without any way to opt out, so I'll take a look. Though I have no familiarity with the `oh-my-zsh` system so not sure configuration of plugins are supposed to work, any pointers?

**Comment by hedning** [comment]
I disabled the nix-shell prompt by default (it assumed far too much about how the prompt is set up), making it possible to enable it by putting `prompt_nix_shell_setup` in the zshrc.
