### ISSUE TITLE
Functions with default arguments only get evaluated one layer deep

### ISSUE THREAD

**Issue by ledettwy** [spwhitt/nix-zsh-completions#11]
### System

- nix-zsh-completions version: 4d9e7d9
- ZSH version: 5.4.2
- NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2875.c2b668ee726 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixpkgs-17.09.2875.c2b668ee726, nixos-17.09.2875.c2b668ee726, unstable-18.03pre125026.f607771d0f5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### Completion trace

https://gist.github.com/ledettwy/5a6d462ca23c3b9f94333b4944012c00

### Issue Description

I have a small little Nix file which demonstrates this behavior. When the top-level expression is a function, nix-zsh-completions seems to have no issue evaluating it to find out what's at the next layer, as long as the arguments have default values. But this only seems to work one level deep - attributes that are further nested that are behind similar functions (with default values for all args) don't get picked up by nix-zsh-completion.

Here's the example code:
<pre>
{ arg1 ? "hi" }:
{ attr1 =
    { arg2 ? "there" }:
    { attr2 =
        { arg3 ? "alice" }:
        "${arg1}${arg2}${arg3}";
    };
}
</pre>

`nix-instantiate --eval argtest.nix -A <TAB>` produces `nix-instantiate --eval argtest.nix -A attr1`, but `nix-instantiate --eval argtest.nix -A attr1.<TAB>` does not produce `nix-instantiate --eval argtest.nix -A attr1.attr2`, even though `attr1.attr2` is valid.

(Note: due to weirdness with Nix, the final string result won't be fully evaluated unless a `--argstr whatever value` is added to the command line (the name and value don't actually matter), like this:
`nix-instantiate --eval argtest.nix --argstr whatever value -A attr1.attr2`.

**Comment by hedning** [comment]
Ah, good catch, I've assumed that the auto-calling magic only happened on the top level, but sure enough it applies to the whole chain when supplying attribute paths on the command line.

I'll see if I can come up with a good solution, the obvious thing (checking if the attribute path is a function, in which case call it) fails on one more recursion since the auto calling magic isn't a language feature, eg. this happens:
```
╰─> nix-repl argtest.nix
Welcome to Nix version 1.11.16. Type :? for help.

Loading ‘argtest.nix’...
Added 1 variables.

+nix-repl> attr1.attr2
error: value is a function while a set was expected, at (string):1:1
```

Shouldn't be too much work traversing the attribute path and calling funtions along the way, though :)

**Comment by hedning** [comment]
Pushed an implementation to master now, seems to work well.

**Comment by ledettwy** [comment]
Works great, thanks!!!
