### ISSUE TITLE
nix 2.0: no completion for custom channels

### ISSUE THREAD

**Issue by ledettwy** [spwhitt/nix-zsh-completions#12]
`nix build nixpkgs.<TAB>` works fine, but if I have a custom channel in my NIX_PATH (e.g., `NIX_PATH=mychannel=/path/to/mychannel`), `nix build mychannel.<TAB>` doesn't provide any suggestions.

**Comment by hedning** [comment]
I'm unable to reproduce this:
```
> NIX_PATH=foo=/home/hed/nixpkgs/
> nix run foo.<tab>
```
This gives completion for me (where `/home/hed/nixpkgs` is a nixpkgs checkout).

You're sure that `import /path/to/mychannel` evaluates to either a set or an autocallable function?

**Comment by ledettwy** [comment]
It works if the custom channel is nixpkgs, but it's not working on my custom channel.  Typing out the full nix build command and running it starts the build successfully though. The top-level is a manually defined set, so I would think that it should be able to auto-complete at least that far.

**Comment by hedning** [comment]
Ah, right, found the problem. When building the `NIX_PATH` expressions I've wrongly assumed that they're functions. Hopefully the last code with that faulty assumption.

Thanks :)

**Comment by ledettwy** [comment]
Awesome, working now! As always, thanks for your amazing responsiveness :)
