### ISSUE TITLE
trace output getting picked up as attributes

### ISSUE THREAD

**Issue by ledettwy** [spwhitt/nix-zsh-completions#13]
It looks like trace output is getting picked up and parsed as attrset keys on 75f820f593cdfb489d55998eddeded437d10aadd. I'm seeing suggestions like this:

<pre>
nix-build -A my.path.(TAB)
\[﻿        \]        \{...\}        trace:        validkey1        validkey2
</pre>

I'm using nix-build from Nix 2.0 if that makes a difference.

**Comment by hedning** [comment]
Right, looks like the way I'm handling errors doesn't work with trace. I'm merging stderr and stdout, displaying a message with the error if the evaluation fails (which can be pretty useful), but that obviously doesn't work well when using `builtins.trace`.

Will push a fix, and rethink how to display errors properly.
