### ISSUE TITLE
Make nix-build completions more like path completions

### ISSUE THREAD

**Issue by ledettwy** [spwhitt/nix-zsh-completions#6]
Currently, completing nested data structures in nix-build produces the entire current selection in the autocomplete choices, for instance:

nix-build -A foo.bar.(TAB)
foo.bar.baz
foo.bar.bop
foo.bar.bezel

For deeply nested data structures, this can get incredibly unwieldy to try to tab through, since the size of the suggestions will grow over time.  Instead, it should probably work like how ZSH autocompletes regular filesystem paths, suggesting only the next layer at each level:

nix-build -A foo.bar.(TAB)
baz
bop
bezel

**Comment by hedning** [comment]
Agreed that seems more consistent and sane. I have a fix using the `_sep_parts` function (`_multi_parts`, which I think is used in file completion used way too much time doing a bunch of weird stuff). Should be in the next release in a few days :)

**Comment by ledettwy** [comment]
That's great to hear! Thanks!
