### ISSUE TITLE
Trouble installing on macOS

### ISSUE THREAD

**Issue by mightybyte** [spwhitt/nix-zsh-completions#7]
I followed the instructions in the README of cloning this repo into `~/.oh-my-zsh/custom/plugins/nix` and adding nix to the plugin list in `~/.zshrc`, but it doesn't seem to be working.

When I type `nix-env <TAB>`, I get:

```
_arguments:comparguments:312: invalid argument: +
```

When i type `nix-build <TAB>`, I get:

```
_nix_shortcuts:1: unknown file attribute: i
_nix_shortcuts:1: unknown file attribute: i
_nix_shortcuts:1: unknown file attribute: i
```

**Comment by olejorgenb** [comment]
Could you post the result of [_complete_debug](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#index-_005fcomplete_005fdebug-_0028_005eX_003f_0029) here?

Simply do a `C-x ?` (default binding) instead of completion. You should get something like:

    $ nix-build 
    Trace output left in /tmp/zsh23272nix-build3 (up-history to view)

The file is usually huge so attaching it through some pastebin might be a good idea.

`zsh --version`  and `nix-env --version` be helpful also.

**Comment by mightybyte** [comment]
zsh 5.0.8 (x86_64-apple-darwin15.0)
nix-env (Nix) 1.11.15

https://gist.github.com/mightybyte/33fed8318386983cd1b6064edba67034

**Comment by hedning** [comment]
Okay, I'm able to reproduce the issue with 5.0.8.

Seeing that 5.0.8 is quite old I'd recommend just upgrading to fix the issue. There seemed to be some major breakage with that version (eg. completion for the `nix` command hangs the shell) so I don't think it's worth the time fixing backwards compatibility.

**Comment by hedning** [comment]
Tested out zsh 5.2, where the `nix-env` error is also produced as we're using the `+ group` feature which isn't supported by yet. That's an easy fix, so 5.2 or anything newer should work.

**Comment by mightybyte** [comment]
I just upgraded to this version of zsh:

    zsh 5.4.2 (x86_64-apple-darwin15.6.0)

Problem still persists

**Comment by hedning** [comment]
Which problem? The first problem with `nix-env` can't happen in 5.4.2, the second is pretty unlikely. If you're still getting the exact same issues do this to make sure you're actually running the new version of ZSH:
```
print $ZSH_VERSION
```

If you're getting some new issue please describe it fully, preferably in a new github issue (I don't have a mac so can't test things fully, but I know that people are using the completion scripts successfully on mac).

**Comment by mightybyte** [comment]
Thanks!  The new version wasn't getting picked up as my login shell, but `zsh --version` was still showing me the new one.  It looks like everything works now.
