### ISSUE TITLE
"nix log ." completion yields shift error/warning

### ISSUE THREAD

**Issue by dtzWill** [spwhitt/nix-zsh-completions#9]
```
$ nix log .<tab>
_sep_parts:shift:127: shift count must be <= $#
```

(Completion does not proceed)

`nix log ./` emits the same message but completion seems to work anyway.

### System

- nix-zsh-completions version: 
0.3.7
- ZSH version: 
5.4.2
- NIX_PATH: 
`nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels:allvm=/home/will/.nix-defexpr/channels/allvm`

#### nix-info

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.76, NixOS, 18.03.git.d4490ef (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12dtz5853_4d8dfd7`
 - channels(will): `"allvm, unstable-18.03pre124015.f59a0f7f1a6"`
 - channels(root): `"nixos-18.03pre124947.33a4de2941d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### Completion trace

(renamed ".log" to make github happy)
[nix-log-dot.log](https://github.com/spwhitt/nix-zsh-completions/files/1627420/nix-log-dot.log)

**Comment by hedning** [comment]
Ah, right, think I ran into this problem a few days ago. The error is an easy fix.

I'm guessing the ideal behavior would be to complete `.` to `./`, not `./.` (`./.` is the ruselt when simply guarding against the attribute completion error). Will have a think about how to make that happen.

**Comment by dtzWill** [comment]
Thanks! I hit this frequently, avoiding the error is much nicer :).

Will add an override to use this on my machines, thanks!
